enable minikube in docker for our dev container
ChorusOne/hopper-build-container pull request #1
Opened 2021-12-21 14:20 UTC by jenpaff

implemented following as per the following doc & repo: https://github.com/microsoft/vscode-dev-containers/tree/main/containers/kubernetes-helm-minikube

manual testing: 
- [X] run Postgres image, set auth token & run integration tests (same steps as in the pipeline) 
- [X] run `./do.sh start-testnet` to startup minikube cluster for testing 

if we can create a release, I can further test it on my current branch

2021-12-21 14:36 UTC, jenpaff commented on library-scripts/rust-debian.sh
> -rustup component add rls rust-analysis rust-src rustfmt clippy 2>&1
fails otherwise: https://github.com/ChorusOne/hopper-build-container/runs/4595918389?check_suite_focus=true is it ok to remove?

2021-12-21 14:44 UTC, QAston commented on library-scripts/rust-debian.sh
> -rustup component add rls rust-analysis rust-src rustfmt clippy 2>&1
Yup, if it's no longer there it's fine to remove it

2021-12-21 14:52 UTC, QAston commented
> if we can create a release, I can further test it on my current branch

You should be able to create a pre-release from your branch, release with a version like v6-prerelease-1 and mark it as prerelease in github

2021-12-21 15:00 UTC, jenpaff commented
> > if we can create a release, I can further test it on my current branch
> 
> You should be able to create a pre-release from your branch, release with a version like v6-prerelease-1 and mark it as prerelease in github

Oh cool! I'll look into that

2021-12-21 15:02 UTC, QAston commented
![image](https://user-images.githubusercontent.com/126822/146951512-fd07c8e8-5a07-474d-a790-2535585384af.png)

Yup, I tested it and the job has been triggered. Bump the prerelease number for additional testing

2021-12-21 15:12 UTC, QAston requested changes
Let's wait with merging until you get the github action to work in the hopper repo

2021-12-21 15:22 UTC, QAston commented on Dockerfile
> +ARG USE_MOBY="true"
it's probably better to use docker cli instead of moby since that's what we've been using so far (and that's what I assume the docker-compose testing environment uses)

2021-12-21 15:31 UTC, QAston commented
Some general notes about this:

* that vscode dev containers repo we've been using isn't made for use in github actions, some things might need tweaking to be able to run in gh actions, feel free to ask for help about actions since I've already figured some of this stuff up when I fixed the rust installation scripts
* I thought it might be needed to replace the "docker-in-docker" https://github.com/microsoft/vscode-dev-containers/tree/main/containers/docker-in-docker part of this with "docker-from-docker" (https://github.com/microsoft/vscode-dev-containers/tree/main/containers/docker-from-docker) but now that I think about it, it might not be needed because minikube has it's own docker anyways. Noting this here just in case

2021-12-21 15:45 UTC, QAston commented on Dockerfile
> +ARG USE_MOBY="true"
nvm, looks like moby installs the commands as docker

2021-12-22 14:03 UTC, QAston commented on library-scripts/rust-debian.sh
> -rustup component add rls rust-analysis rust-src rustfmt clippy 2>&1
You should re-add rls now. It won't change the build's output but it's useful for vscode when using the devcontainer

2021-12-29 10:54 UTC, QAston commented on Dockerfile
> +    && sudo apt-get -y install postgresql \
a better way to do it is to use postgres installed by nix-shell, there's no need to install postgres here

2021-12-29 11:38 UTC, jenpaff commented on Dockerfile
> +    && sudo apt-get -y install postgresql \
ok I can try that

2022-01-05 14:57 UTC, QAston commented
Let's close this one for now, we might still need docker minikube or kubectl in the future

2022-01-05 14:57 UTC, closed without merging